springdoc:
  api-docs:
    path: /api-docs

spring:
  profiles:
    include:
      - secret

  application:
    name: MyHouseStair

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 200MB
      location: ./tmp
      max-file-size: 200MB
      max-request-size: 200MB

  datasource:
    driver-class-name: ${oracle.driver-class-name}
    url: ${oracle.url}
    username: ${oracle.username}
    password: ${oracle.password}

  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true
        default_batch_fetch_size: 100

aws:
  s3:
    bucket-name: my-house-stair-bucket
    access-key: ${aws.access-key}
    secret-key: ${aws.secret-key}